export const UPDATE_CHAT_MSG_LIST = 'UPDATE_CHAT_MSG_LIST';
export const UPDATE_JOINED_LIST = 'UPDATE_JOINED_LIST';
export const UPDATE_LEFT_LIST = 'UPDATE_LEFT_LIST';
export const ADD_TYPED_LIST = 'ADD_TYPED_LIST';
export const REMOVE_TYPED_LIST = 'REMOVE_TYPED_LIST';
export const ONLINE_USER_LIST = 'ONLINE_USER_LIST';
